### ISSUE TITLE
Crash @ drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed

### ISSUE THREAD

**Issue by C0rn3j** [DrZhark/mocreatures#1]
Mod: mocreatures{10.0.4}
Forge: 2105
http://pastebin.com/UuA4gfh8

**Comment by Divineaspect** [comment]
ditto, mostly replying to follow this issue.

**Comment by DrZhark** [comment]
pulling my hair trying to fix this thing! :)

**Comment by C0rn3j** [comment]
> ditto, mostly replying to follow this issue.

You can just click the Subscribe button.

**Comment by DrZhark** [comment]
a new update 10.0.5 has been released that could fix the error. pending testing

**Comment by AfterRebelion** [comment]
I didn't have any crash yet, will continue testing.
**EDIT:**
[I was too soon to talk](https://gist.github.com/AfterRebelion/1a4d61af0779504c01ffa0c1e7c09384)

**Comment by sironin** [comment]
Also getting this problem in 10.0.5.  Except with Anchovy.

**Comment by DrZhark** [comment]
the fix involves changing code in CustomMobSpawner, I'll release an updated file tonight.

**Comment by Shybella** [comment]
Sweet, yes having this problem too. Thank you for keeping this mod up to date.

**Comment by DrZhark** [comment]
CustomMobSpawner 3.10.1 updated, it seems to fix the bug. Please test

**Comment by Shybella** [comment]
All good, no problems yet.

**Comment by C0rn3j** [comment]
Seems to work great

**Comment by MagmaSlime123** [comment]
> All good, no problems yet.

You have 200+ issues. Read them.

**Comment by MagmaSlime123** [comment]
> CustomMobSpawner 3.10.1 updated, it seems to fix the bug. Please test

You have 200+ issues. Fix them.
