### ISSUE TITLE
I don't see the animals!!!

### ISSUE THREAD

**Issue by Elizabethgamer23** [DrZhark/mocreatures#190]

**Comment by ghost** [comment]
Have you tried downloading the mods from the [official website](mocreatures.org)? I had this problem before but managed to make it work by downloading the mods from the official website.

EDIT: For some reason, I can't download the mods from it at the moment.

**Comment by syndicate25** [comment]
Well one can only assume you're using the latest version.  If you're on 1.12.2, then do what adorski said and use the official downloads only.

https://www.curseforge.com/minecraft/mc-mods/mo-creatures/

OR

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272337-mo-creatures-v12-0-0-for-minecraft-1-12-1-now

OR

https://www.mocreatures.org/downloads

**Comment by IceT2** [comment]
I'm not sure if you've tried the links lately ......... I just have :
https://www.mocreatures.org/downloads  ..... has adfly links that go no-where

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272337-mo-creatures-v12-0-0-for-minecraft-1-12-1-now ........ has adfly links that go no-where, only the 1.12.1 diret links work, but I'm not sure if anyone will still use a 1.12.1 version.

https://www.curseforge.com/minecraft/mc-mods/mo-creatures/ ...... has links that will download the mod, but the filename will be 'DrZharks+MoCreatures+Mod-12.0.5.jar' (for example, the 1.12.2 version) and for many (myself included), this makes the animals invisible when you start your game. 
Personally, by renameing the file from 'DrZharks+MoCreatures+Mod-12.0.5.jar' to 'MoCreatures.jar' has been the only way I've been able to make the animals visible.

**Comment by syndicate25** [comment]
I did test them today. There is even a direct link on the MCF page that doesn't need adfly which works fine.  But yes, I did forget to mention that you have to remove the + from the file name as well so thank you for bringing that up.

**Comment by Szand0r** [comment]
Simply rename from DrZharks + MoCreatures + Mod-12.0.5.jar to DrZharksMoCreaturesMod-12.0.5.jar, then it works ... it's only because of the file name of the jar file

**Comment by angulcumclean** [comment]
I downloaded this mod after finally leaving 1.10.2 to 1.12.2 and all I see is the shadow of the animal (like the little circle under them) and I see bubbles in the water where I guess the ducks are supposed to be, but I don't see any of the actual animals :/

**Comment by syndicate25** [comment]
Did you try everything mentioned here already....?

**Comment by angulcumclean** [comment]
> Did you try everything mentioned here already....?

Oh omg I didn't even see the part about renaming the file I'm going to try that now, I rename the actual jar file to "MoCreatures.jar" yes?

**Comment by syndicate25** [comment]
Sure. You can just take the +'s out and that would be sufficient.

**Comment by Elizabethgamer23** [comment]
Thank you guys so much for your help I got it working!
