### ISSUE TITLE
Great Issue: is not being updated

### ISSUE THREAD

**Issue by ghost** [DrZhark/mocreatures#193]
minecraft 1.12 was 7 6 2017

**Comment by syndicate25** [comment]
This is not an issue. Don't fill someone's Github with this garbage, please.

**Comment by MagmaSlime123** [comment]
No need to be rude. This can be updated, but due to the source not being given then it's essentially pointless in this existing at all.

**Comment by syndicate25** [comment]
> No need to be rude. This can be updated, but due to the source not being given then it's essentially pointless in this existing at all.

Mo Creatures has been open source for a good while now.

**Comment by MagmaSlime123** [comment]
Well, no link is on the Curse page.

**Comment by syndicate25** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272337-mo-creatures-v12-0-0-for-minecraft-1-12-1-now
