### ISSUE TITLE
invisible creatures in 1.8.9

### ISSUE THREAD

**Issue by IamRuNiX** [DrZhark/mocreatures#223]
so they spawn but i can only see the shadow and i didnt find this mob spawner thing or a resource pack for that version so what should i do?

**Comment by CapivaraTupiniquim** [comment]
O site para download é esse mas é bem chato https://www.mocreatures.org/downloads, e se ainda não resolver tira os "+" do nome do mod.

**Comment by IamRuNiX** [comment]
it worked now thanks alot :)
