### ISSUE TITLE
many issues with Custom Mob Spawner

### ISSUE THREAD

**Issue by 0Navis0** [DrZhark/mocreatures#37]
Custom Mob Spawner seems to override totally how the mobs spawn normally.

It doesn't support at all modded biomes other than BOP ones like AbyssalCraft and Thaumcraft ones, and has a bad support for BOP biomes, some BOP biomes are almost empty while others are full of mobs.

It has too a bad support for all modded mobs other than MoCreatures ones, causing them to spawn incorrectly or not at all in many biomes.

The increasing of mob spawn frequence durring Blood Moon from the mod of the name doesn't work too.

**Comment by Hypsellis** [comment]
I add the Thaumcraft magic forest and tainted land in the list of biomes which aren't supported.

**Comment by Hypsellis** [comment]
Custom Mob Spawner seems to override totally how the mobs spawn normally. 
It doesn't support at all modded biomes other than BOP ones, and has a bad support for BOP biomes, some BOP biomes are almost empty while others are full of mobs. It has too a bad support for all modded mobs other than MoCreatures ones, causing them to spawn incorrectly or not at all in many biomes. 
The increasing of mob spawn frequence durring Blood Moon from the mod of the name doesn't work too.

**Comment by snurre0** [comment]
I agree, have had the same observations.
Really a lot of mobs in some biomes, others completely empty. Also with BOP. 

I also have a problem where vanilla mobs(so far only vanilla) spawn next to a tourch, one block away maybe. When I throw an item in that exact spot, it renders as if it's really dark.
I really don't know what's going on, but I never had this issue before I recently added this mod to my server.

**Comment by 0Navis0** [comment]
Custom Mob Spawner isn't necessary for MoCreatures works, it works even better without. The only problem is that aquatic mobs don't spawn.

**Comment by 0Navis0** [comment]
This mod is really the worst I saw. The configuration is incomprehensible. There are so many files and so many texts inside.

The mod overrides and modifies totally the original spawn mechanics of vanilla and other mods without giving the choice to keep the original spawn mechanic. 

The mobs don't spawn more like they should, it destroys all the other mods toke so much time to do. 
Many mobs and biomes aren't supported, it's fucking hard to configure correctly, and many biomes are full of mobs while other totally empty. 

This mod maybe started with good intentions, but the result is just totally failed. The best thing would be to abandon it or rewrite it, and use a normal configuration file for configuring how the MoCreatures mob spawn, and not override all the other mods mobs spawn, or at least give the choice for it.

**Comment by EchenCraft** [comment]
Didnt realize this thread was exactly the same as the one I just poosted but yea I agree with Hypsellis.

I have a total of 661 config files and there is no way I could possibly find time to tweak all of them to sort out the various issues its causing but without it we get no marine animals at all. The focus here should be fix the spawning of aquatic animals and get rid of CMS or completely overhaul CMS which would probably be more work than its worth.

**Comment by Kambyo** [comment]
How do I make the server work without custom mob spawner?

**Comment by Kambyo** [comment]
the servers closes automatically when I try to enter without custom mob spawner

"Ticking entity java.lang.NoClassDefFoundError: drzhark/customspawner/utils/CMSUtils"

**Comment by 0Navis0** [comment]
It works only in Client without CustomMobSpawner, but it doesn't work correctly.

**Comment by Kambyo** [comment]
Thanks for the help, but I eliminated config and it is working now...
What do you mean by it doesn't work correctly? I don't care about water mobs! ;D
