### ISSUE TITLE
Jellyfish crash client to desktop

### ISSUE THREAD

**Issue by kaitoyuuki** [DrZhark/mocreatures#4]
As far as I can tell from the log file, a jellyfish spawned near me, and my game crashed.
here's the crash report.
https://gist.github.com/kaitoyuuki/485c3a4ce1e3ffe1ab91401b931f87cf

**Comment by DrZhark** [comment]
same issue tracked on another thread

**Comment by MagmaSlime123** [comment]
> same issue tracked on another thread

You have 200+ issues. Fix them.

**Comment by SlimeProgenitor** [comment]
> 
> 
> > same issue tracked on another thread
> 
> You have 200+ issues. Fix them.

my dude, this mod hasn't updated since 2018. Give up on anything getting fixed. It's an abandoned mod.

**Comment by MagmaSlime123** [comment]
Why is it still here and on Curse then.
