### ISSUE TITLE
[1.12.2] All kind of insects flying on the ground

### ISSUE THREAD

**Issue by Draskh** [DrZhark/mocreatures#76]
The most insects fly on the ground and not in the air. They are not able to go over blocks or anything. Birds seem to be not affected. 
The first image shows bees that cannot fly.
![2017-12-06_12 40 34](https://user-images.githubusercontent.com/26455012/33713295-fe1c1f5c-db4a-11e7-8b34-1347bf3f7e84.png)
The second image shows a butterfly that cannot escape of a boar.
![2017-12-05_12 59 00](https://user-images.githubusercontent.com/26455012/33713315-0d7cf714-db4b-11e7-9f8b-952df32bfa13.png)

**Comment by C0rn3j** [comment]
Just a FYI, this bug tracker is dead and the development team is openly hostile to anyone running this mod along other mods, as discussed here.

https://github.com/DrZhark/mocreatures/issues/72

**Comment by JonasCiss** [comment]
It is easy to claim such things. If the author wish to let the mod go dead you cannot change that.

**Comment by JonasCiss** [comment]
You hadn't success with your first try on discord. The author woundn't be amused reading this again.

**Comment by Draskh** [comment]
Seems this is dead now. I will try the website, http://www.mocreatures.org/ .
